#!/usr/bin/env bash
chromium \
  --app=https://gemini.google.com \
  --class=WebApp-ChatGPT \
  --user-data-dir="$HOME/.local/share/webapps/chatgpt" \
  --new-window \
  --enable-features=UseOzonePlatform,WaylandWindowDecorations,WebRTCPipeWireCapturer \
  --ozone-platform-hint=wayland
